Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,17 +40,17 @@ jobs:
         - name: Run Test and create report
           run: python -m robot -d reports -x junit-report.xml "testcases/"
           
-        - name: Run Robot Framework tests and generate report
-          run: |
-             echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
-        # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
-        #   if: env.ROBOT_RC != '0'
+        # - name: Run Robot Framework tests and generate report
         #   run: |
-        #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
-        #     exit 1
+        #      echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
+        # # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
+        # #   if: env.ROBOT_RC != '0'
+        # #   run: |
+        # #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
+        # #     exit 1
         
-        - name: Publish test results
-          uses: actions/upload-artifact@v2
-          with:
-            name: robot-test-results
-            path: results
+        # - name: Publish test results
+        #   uses: actions/upload-artifact@v2
+        #   with:
+        #     name: robot-test-results
+        #     path: results
